import Link from "next/link";

export const metadata = {
  title: "Privacy policy — Simulyn AI",
  description:
    "How Simulyn AI collects, uses, and protects your data. Placeholder — swap for legal-reviewed copy before paid customers.",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <Link
        href="/"
        className="text-xs text-site-accent hover:underline"
      >
        &larr; Back to Simulyn AI
      </Link>
      <h1 className="mt-6 text-3xl font-bold text-white">Privacy policy</h1>
      <p className="mt-2 text-xs text-site-muted">
        Last updated: {new Date().toISOString().slice(0, 10)}
      </p>

      <div className="mt-6 rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200">
        <strong>Placeholder.</strong> Before taking payment from customers,
        replace this content with a legally-reviewed privacy policy. Template
        generators: Termly, iubenda, Privacy Policies.com.
      </div>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-slate-300">
        <section>
          <h2 className="text-lg font-semibold text-white">What we collect</h2>
          <p className="mt-2">
            Account data (email, name, password hash), organization data
            (name, billing status), project data (schedule, task details,
            progress) that you upload or create inside Simulyn AI, and basic
            usage telemetry needed to operate the service.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white">How we use it</h2>
          <p className="mt-2">
            To provide the service you signed up for: predict delays, write
            narrative summaries, send weekly recap emails, and secure your
            account. We never sell your data.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white">LLM providers</h2>
          <p className="mt-2">
            Prediction narrative and scenario summaries are generated by a
            large language model provider (OpenAI or Anthropic, depending on
            deployment configuration). Prompts sent to the provider include
            the task name, dates, and progress of the item being scored — but
            no personal information beyond the email you registered with.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white">Retention &amp; deletion</h2>
          <p className="mt-2">
            You can delete your account and organization at any time from the
            Organizations page. Deleting an organization deletes all its
            projects, tasks, predictions, and simulations. Database backups
            are retained for 30 days.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-white">Contact</h2>
          <p className="mt-2">
            Questions about this policy, data requests, or anything else:{" "}
            <a
              href="mailto:hello@simulyn.ai"
              className="text-site-accent hover:underline"
            >
              hello@simulyn.ai
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
