"""
Simulyn AI — Risk engine + LLM-powered narrative + chat copilot.

Numeric outputs (risk_level, delay_days, predicted_delay) are computed by a
deterministic rule engine so they are predictable and auditable. The narrative
fields (summary, recommendation, impact_summary) are generated by an LLM
(OpenAI, Anthropic, or a local Ollama server) when configured, otherwise we
fall back to canned text so local dev still works.

The /chat-step endpoint powers the multilingual chat copilot. It is stateless:
it receives the full conversation + available tool schemas, asks the LLM for
one step (tool_call or final answer), and returns it. The .NET orchestrator
executes tools in-process and loops back. See backend ChatOrchestrator.cs.

Environment variables:
  LLM_PROVIDER         openai | anthropic | ollama | auto | off   (default: auto)
  OPENAI_API_KEY       enables OpenAI provider (also: Groq / DeepSeek / Together /
                       OpenRouter — any OpenAI-compatible API, via OPENAI_BASE_URL)
  ANTHROPIC_API_KEY    enables Anthropic provider
  OPENAI_BASE_URL      default: unset (→ https://api.openai.com/v1). Override to use
                       any OpenAI-compatible endpoint: Groq, DeepSeek, Together, etc.
  OPENAI_MODEL         default: gpt-4o-mini (narrative: /predict, /simulate,
                       /project-brief, /weekly-recap)
  OPENAI_CHAT_MODEL    default: inherits OPENAI_MODEL. Override to use a different
                       model for /chat-step (e.g. a larger tool-capable model).
  ANTHROPIC_MODEL      default: claude-3-5-haiku-latest
  OLLAMA_BASE_URL      default: http://localhost:11434/v1
  OLLAMA_MODEL         default: llama3.2 (for /predict, /simulate, and /chat-step
                       when OLLAMA_CHAT_MODEL is not set)
  OLLAMA_CHAT_MODEL    default: inherits OLLAMA_MODEL. Override with a tool-capable
                       model like llama3.1:8b or qwen2.5:7b for better chat quality.
  OLLAMA_TIMEOUT_SECS  default: 60   (local CPU inference can be slow)
  LLM_TIMEOUT_SECS     default: 8    (used for OpenAI / Anthropic)
  LLM_MAX_TOKENS       default: 350
  CHAT_MAX_TOKENS      default: 700  (chat replies can be longer than predict)
"""
from __future__ import annotations

import json
import logging
import os
import re
from datetime import date, datetime, timedelta
from typing import Any, Literal, Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# Load .env.local (preferred, gitignored) then .env as fallback. Process
# environment variables always win so container-level secrets override the file.
try:
    from dotenv import load_dotenv

    _here = os.path.dirname(os.path.abspath(__file__))
    load_dotenv(os.path.join(_here, ".env.local"), override=False)
    load_dotenv(os.path.join(_here, ".env"), override=False)
except ImportError:
    pass  # python-dotenv not installed → rely on process env only

logger = logging.getLogger("simulyn.ai")
logging.basicConfig(level=logging.INFO)


# ---------------------------------------------------------------------------
# LLM configuration
# ---------------------------------------------------------------------------

LLM_PROVIDER_ENV = os.getenv("LLM_PROVIDER", "auto").lower()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
# Chat can use a different model than narrative (e.g. cheaper/smaller for chat,
# or a larger tool-capable model when narrative uses a cheap one). Inherits
# OPENAI_MODEL if unset.
OPENAI_CHAT_MODEL = os.getenv("OPENAI_CHAT_MODEL") or OPENAI_MODEL
# Optional override for the OpenAI API base URL. Leave unset for OpenAI itself;
# set to provider-specific endpoint for Groq, DeepSeek, Together AI, OpenRouter,
# Azure OpenAI, etc. All of them speak the OpenAI protocol, so no code changes
# are needed — only env vars.
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL") or None
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-3-5-haiku-latest")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2")
# Chat needs tool-calling. If the operator has explicitly set OLLAMA_CHAT_MODEL,
# honour it; otherwise inherit OLLAMA_MODEL so a single env var drives every
# endpoint. Override with `llama3.1:8b` or `qwen2.5:7b` for better tool-call fidelity.
OLLAMA_CHAT_MODEL = os.getenv("OLLAMA_CHAT_MODEL") or OLLAMA_MODEL
OLLAMA_TIMEOUT_SECS = float(os.getenv("OLLAMA_TIMEOUT_SECS", "60"))
LLM_TIMEOUT_SECS = float(os.getenv("LLM_TIMEOUT_SECS", "8"))
LLM_MAX_TOKENS = int(os.getenv("LLM_MAX_TOKENS", "350"))
CHAT_MAX_TOKENS = int(os.getenv("CHAT_MAX_TOKENS", "1500"))

ProviderName = Literal["openai", "anthropic", "ollama", "off"]


def _resolve_provider() -> ProviderName:
    if LLM_PROVIDER_ENV == "off":
        return "off"
    if LLM_PROVIDER_ENV == "ollama":
        return "ollama"  # always try; we'll fall back gracefully if unreachable
    if LLM_PROVIDER_ENV == "openai":
        return "openai" if OPENAI_API_KEY else "off"
    if LLM_PROVIDER_ENV == "anthropic":
        return "anthropic" if ANTHROPIC_API_KEY else "off"
    # auto: prefer hosted providers when keys are present, otherwise off.
    # Ollama is opt-in only because we don't probe at startup.
    if OPENAI_API_KEY:
        return "openai"
    if ANTHROPIC_API_KEY:
        return "anthropic"
    return "off"


PROVIDER: ProviderName = _resolve_provider()
if PROVIDER == "openai":
    logger.info(
        "Simulyn AI starting — LLM provider: openai (base_url=%s, model=%s, chat_model=%s)",
        OPENAI_BASE_URL or "https://api.openai.com/v1 (default)",
        OPENAI_MODEL,
        OPENAI_CHAT_MODEL,
    )
elif PROVIDER == "ollama":
    logger.info(
        "Simulyn AI starting — LLM provider: ollama (base_url=%s, model=%s, chat_model=%s)",
        OLLAMA_BASE_URL,
        OLLAMA_MODEL,
        OLLAMA_CHAT_MODEL,
    )
else:
    logger.info("Simulyn AI starting — LLM provider: %s", PROVIDER)

_openai_client = None
_anthropic_client = None
_ollama_client = None


def _get_openai():
    """Returns an AsyncOpenAI client pointed at OPENAI_BASE_URL when set.

    OPENAI_BASE_URL unlocks any OpenAI-compatible provider without code changes:
    - Groq:      https://api.groq.com/openai/v1
    - DeepSeek:  https://api.deepseek.com/v1
    - Together:  https://api.together.xyz/v1
    - OpenRouter:https://openrouter.ai/api/v1
    - Azure:     https://<resource>.openai.azure.com/openai/deployments/<dep>
    """
    global _openai_client
    if _openai_client is None:
        from openai import AsyncOpenAI

        kwargs = {"api_key": OPENAI_API_KEY, "timeout": LLM_TIMEOUT_SECS}
        if OPENAI_BASE_URL:
            kwargs["base_url"] = OPENAI_BASE_URL
        _openai_client = AsyncOpenAI(**kwargs)
    return _openai_client


def _get_anthropic():
    global _anthropic_client
    if _anthropic_client is None:
        from anthropic import AsyncAnthropic

        _anthropic_client = AsyncAnthropic(api_key=ANTHROPIC_API_KEY, timeout=LLM_TIMEOUT_SECS)
    return _anthropic_client


def _get_ollama():
    """Reuse the OpenAI SDK against Ollama's OpenAI-compatible endpoint.
    Ollama accepts any non-empty api_key string."""
    global _ollama_client
    if _ollama_client is None:
        from openai import AsyncOpenAI

        _ollama_client = AsyncOpenAI(
            api_key="ollama",
            base_url=OLLAMA_BASE_URL,
            timeout=OLLAMA_TIMEOUT_SECS,
        )
    return _ollama_client


# ---------------------------------------------------------------------------
# FastAPI
# ---------------------------------------------------------------------------

app = FastAPI(title="Simulyn AI Engine", version="0.2.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _parse(d: str) -> date:
    return datetime.strptime(d[:10], "%Y-%m-%d").date()


# ---------------------------------------------------------------------------
# Deterministic rule engine (unchanged math)
# ---------------------------------------------------------------------------

def predict_delay(
    task_start: date,
    task_end: date,
    progress: int,
    today: Optional[date] = None,
) -> tuple[str, int, int, int]:
    """Return (risk_level, delay_days, expected_progress, gap_pct)."""
    t = today or date.today()
    total_days = max(1, (task_end - task_start).days)
    elapsed = max(0, min((t - task_start).days, total_days))
    expected = round(100.0 * elapsed / total_days) if total_days else 100
    gap = expected - progress

    if gap <= 5:
        risk = "Low"
        delay_days = max(0, gap // 5)
    elif gap <= 15:
        risk = "Medium"
        delay_days = max(1, gap // 3)
    else:
        risk = "High"
        delay_days = max(2, gap // 2)

    return risk, delay_days, expected, gap


def _fallback_predict_text(risk: str, expected: int, progress: int) -> tuple[str, str]:
    summary = f"Expected progress ~{expected}% vs actual {progress}%."
    if risk == "High":
        rec = (
            "• Add 2 workers\n"
            "• Increase working hours\n"
            "• Re-sequence dependent trades"
        )
    elif risk == "Medium":
        rec = "• Add 1 worker or extend shift\n• Review blockers daily"
    else:
        rec = "• Monitor weekly; no immediate action"
    return summary, rec


def _fallback_simulate_text(
    input_delay: int, predicted: int, new_end: date, task_count: int
) -> str:
    return (
        f"With an input slip of {input_delay} day(s), the model estimates "
        f"~{predicted} day(s) impact on the project finish "
        f"(new end ≈ {new_end.isoformat()}, {task_count} tasks in scope)."
    )


# ---------------------------------------------------------------------------
# LLM prompts
# ---------------------------------------------------------------------------

PREDICT_SYSTEM_PROMPT = (
    "You are Simulyn AI, an assistant for construction project managers. "
    "You write short, concrete, trade-aware delay analyses and mitigation plans. "
    "Never invent project facts that are not provided in the user message. "
    "Do not restate the risk level — the UI already shows it. "
    "A busy site engineer must be able to act on your output in under a minute."
)

SIMULATE_SYSTEM_PROMPT = (
    "You are Simulyn AI, advising a construction project manager on a what-if delay "
    "scenario. Explain the impact in plain language and suggest one or two practical "
    "mitigations. Never invent project facts that are not provided. Be concise."
)

PROJECT_BRIEF_SYSTEM_PROMPT = (
    "You are Simulyn AI, writing a one-glance project health brief for a busy "
    "construction project manager. The numeric health score is already computed "
    "and shown in the UI — do not repeat it. Write in plain English, concrete and "
    "trade-aware. Never invent facts that are not in the input. No markdown."
)

WEEKLY_RECAP_SYSTEM_PROMPT = (
    "You are Simulyn AI, writing a short weekly recap for a construction leader "
    "across their whole portfolio. Call out what changed, where the biggest risk "
    "sits, and what they should pay attention to this week. Ground every bullet in "
    "the numbers provided. Never invent projects or figures. No markdown headings."
)


def _build_predict_user_prompt(
    task_name: str,
    task_start: date,
    task_end: date,
    progress: int,
    expected: int,
    gap: int,
    risk: str,
    delay_days: int,
    project_start: date,
    project_end: date,
) -> str:
    return (
        f"Task: {task_name}\n"
        f"Task window: {task_start.isoformat()} -> {task_end.isoformat()}\n"
        f"Project window: {project_start.isoformat()} -> {project_end.isoformat()}\n"
        f"Today: {date.today().isoformat()}\n"
        f"Reported progress: {progress}%\n"
        f"Expected progress (time-based): {expected}%\n"
        f"Gap (expected - actual): {gap} percentage points\n"
        f"Computed risk level: {risk}\n"
        f"Estimated delay impact: {delay_days} day(s)\n\n"
        "Respond with ONLY a JSON object (no prose, no markdown) with exactly two "
        "string fields:\n"
        '  "summary":        one sentence describing the situation in concrete terms.\n'
        '  "recommendation": a SINGLE JSON string containing 2-4 short mitigation\n'
        "                    bullets. Separate bullets with a literal newline\n"
        "                    character (\\n) inside the string. Each bullet starts\n"
        "                    with \"• \" (bullet + space). Tailor wording to the task\n"
        "                    name (e.g. concrete pour, MEP rough-in, glazing, fitout).\n"
        "                    No markdown headings. Do not split the bullets into\n"
        "                    separate JSON keys or a JSON array.\n\n"
        "Example of the required shape:\n"
        '  {"summary": "Foundation pour is behind schedule...", '
        '"recommendation": "• Call the concrete supplier to confirm Monday delivery\\n'
        '• Add a second crew for the south pour\\n• Reshuffle curing to overlap with rebar tie"}'
    )


def _build_simulate_user_prompt(
    project_id: str,
    input_delay: int,
    project_start: date,
    project_end: date,
    task_count: int,
    predicted: int,
    new_end: date,
) -> str:
    return (
        f"Project window: {project_start.isoformat()} -> {project_end.isoformat()}\n"
        f"Tasks in scope: {task_count}\n"
        f"Hypothetical input delay: {input_delay} day(s)\n"
        f"Model-estimated schedule impact: {predicted} day(s)\n"
        f"Projected new finish date: {new_end.isoformat()}\n\n"
        "Respond with JSON containing exactly one string field:\n"
        '  "impact_summary": 3-5 sentence narrative explaining what this delay means '
        "for the project, who is most affected, and one or two practical mitigations "
        "the project manager could take. No markdown headings."
    )


# ---------------------------------------------------------------------------
# LLM call (provider-agnostic, returns parsed JSON or None)
# ---------------------------------------------------------------------------

async def _llm_json(system_prompt: str, user_prompt: str) -> Optional[dict]:
    if PROVIDER == "off":
        return None

    try:
        if PROVIDER == "openai":
            client = _get_openai()
            resp = await client.chat.completions.create(
                model=OPENAI_MODEL,
                response_format={"type": "json_object"},
                max_tokens=LLM_MAX_TOKENS,
                temperature=0.2,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
            )
            content = (resp.choices[0].message.content or "").strip()

        elif PROVIDER == "ollama":
            # Ollama exposes an OpenAI-compatible Chat Completions API.
            # response_format={"type":"json_object"} is honoured by Ollama
            # (translated to its native JSON mode) for models that support it.
            client = _get_ollama()
            resp = await client.chat.completions.create(
                model=OLLAMA_MODEL,
                response_format={"type": "json_object"},
                max_tokens=LLM_MAX_TOKENS,
                temperature=0.2,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            system_prompt
                            + " Reply with raw JSON only. Do not wrap in markdown."
                        ),
                    },
                    {"role": "user", "content": user_prompt},
                ],
            )
            content = (resp.choices[0].message.content or "").strip()

        elif PROVIDER == "anthropic":
            client = _get_anthropic()
            resp = await client.messages.create(
                model=ANTHROPIC_MODEL,
                max_tokens=LLM_MAX_TOKENS,
                temperature=0.2,
                system=(
                    system_prompt
                    + " Respond with raw JSON only — no prose, no code fences."
                ),
                messages=[{"role": "user", "content": user_prompt}],
            )
            parts = []
            for block in resp.content:
                text = getattr(block, "text", None)
                if text:
                    parts.append(text)
            content = "".join(parts).strip()

        else:
            return None

        if content.startswith("```"):
            stripped = content.strip("`")
            if "\n" in stripped:
                stripped = stripped.split("\n", 1)[1]
            content = stripped.strip()

        return json.loads(content)

    except Exception as exc:
        logger.warning(
            "LLM call failed (provider=%s); falling back to deterministic text. error=%s",
            PROVIDER,
            exc,
        )
        return None


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

class PredictIn(BaseModel):
    task_id: str
    task_name: str
    start_date: str
    end_date: str
    progress: int = Field(ge=0, le=100)
    project_start: str
    project_end: str


class PredictOut(BaseModel):
    risk_level: str
    delay_days: int
    summary: str
    recommendation: str


@app.post("/predict", response_model=PredictOut)
async def predict(body: PredictIn) -> PredictOut:
    ts, te = _parse(body.start_date), _parse(body.end_date)
    ps, pe = _parse(body.project_start), _parse(body.project_end)
    risk, delay_days, expected, gap = predict_delay(ts, te, body.progress)

    summary, recommendation = _fallback_predict_text(risk, expected, body.progress)

    llm_data = await _llm_json(
        PREDICT_SYSTEM_PROMPT,
        _build_predict_user_prompt(
            task_name=body.task_name,
            task_start=ts,
            task_end=te,
            progress=body.progress,
            expected=expected,
            gap=gap,
            risk=risk,
            delay_days=delay_days,
            project_start=ps,
            project_end=pe,
        ),
    )
    if llm_data:
        s = llm_data.get("summary")
        r = llm_data.get("recommendation")
        if isinstance(s, str) and s.strip():
            summary = s.strip()
        if isinstance(r, str) and r.strip():
            recommendation = r.strip()

    return PredictOut(
        risk_level=risk,
        delay_days=delay_days,
        summary=summary,
        recommendation=recommendation,
    )


class SimulateIn(BaseModel):
    """Scenario-aware what-if input.

    The deterministic math is done by the .NET side so every scenario has a
    predictable, auditable number. This service's only job is to dress the
    result in plain-English, trade-aware narrative.

    Legacy callers (pre-3A) can still pass `input_delay_days`/`task_count`
    without `scenario_type`; we treat that as UniformSlip.
    """

    project_id: str
    project_name: Optional[str] = None
    project_start: str
    project_end: str
    task_count: int = Field(ge=0)

    # New scenario-aware fields.
    scenario_type: Optional[str] = None
    config: Optional[dict[str, Any]] = None
    predicted_delay_days: Optional[int] = None
    deterministic_summary: Optional[str] = None
    signals: Optional[dict[str, Any]] = None

    # Legacy (kept for back-compat).
    input_delay_days: Optional[int] = Field(default=None, ge=0)


class SimulateOut(BaseModel):
    predicted_delay: int
    impact_summary: str
    headline: str
    scenario_type: str


def _scenario_hints(scenario_type: str) -> str:
    """Per-type guidance so the narrative reads differently for each scenario."""
    if scenario_type == "UniformSlip":
        return (
            "Scenario: every task slips by the same number of days. "
            "Focus on cumulative effect, trades most exposed to compression, "
            "and where resequencing could claw time back."
        )
    if scenario_type == "SingleTaskSlip":
        return (
            "Scenario: one specific task slips. Call the task out by name. "
            "Mention whether it sits on the critical path (late in the project) "
            "or has room to absorb through re-sequencing."
        )
    if scenario_type == "AddResource":
        return (
            "Scenario: extra crew / capacity has been added. Talk about which "
            "trades realistically scale (e.g. more formwork crews, more electricians) "
            "and the coordination cost that eats into nominal gains."
        )
    if scenario_type == "WeatherPause":
        return (
            "Scenario: weather window forces a pause. Focus on outdoor-exposed "
            "trades (earthworks, roofing, facade) and whether indoor scope can "
            "continue during the pause to soften the impact."
        )
    if scenario_type == "ScopeReduction":
        return (
            "Scenario: tasks have been dropped from scope. Acknowledge the "
            "schedule win but remind the PM of the quality / handover implications."
        )
    return ""


def _build_scenario_user_prompt(body: SimulateIn) -> str:
    scenario_type = body.scenario_type or "UniformSlip"
    predicted = body.predicted_delay_days if body.predicted_delay_days is not None else 0
    direction = (
        "later" if predicted > 0
        else "earlier" if predicted < 0
        else "unchanged"
    )
    signals_txt = ""
    if body.signals:
        parts = [f"  - {k}: {v}" for k, v in body.signals.items()]
        signals_txt = "\nDeterministic signals:\n" + "\n".join(parts)

    return (
        f"Project: {body.project_name or body.project_id}\n"
        f"Project window: {body.project_start} -> {body.project_end}\n"
        f"Tasks in scope: {body.task_count}\n"
        f"Scenario type: {scenario_type}\n"
        f"Deterministic result: {predicted:+d} day(s) ({direction})\n"
        f"{_scenario_hints(scenario_type)}"
        f"{signals_txt}\n"
        "\nDeterministic one-liner (rewrite in your own words, don't quote verbatim):\n"
        f"  {body.deterministic_summary or ''}\n\n"
        "Respond with JSON containing exactly two string fields:\n"
        '  "headline":       short card title, <= 90 chars. Name the trade or task\n'
        '                    where relevant. Example: "Wiring slip + 3 day finish".\n'
        '  "impact_summary": 2-4 sentences: what this scenario means, who is most\n'
        "                    affected, and one or two concrete mitigations.\n"
        "                    Plain text, no markdown, no restating the integer day count."
    )


@app.post("/simulate", response_model=SimulateOut)
async def simulate(body: SimulateIn) -> SimulateOut:
    scenario_type = body.scenario_type or "UniformSlip"
    ps, pe = _parse(body.project_start), _parse(body.project_end)

    # Legacy back-compat: if the caller didn't pre-compute a predicted delay,
    # fall back to the old UniformSlip math here so pre-3A demos still work.
    if body.predicted_delay_days is None:
        input_delay = body.input_delay_days or 0
        predicted = round(input_delay * (1 + body.task_count * 0.05))
        det_summary = (
            body.deterministic_summary
            or _fallback_simulate_text(
                input_delay, predicted, pe + timedelta(days=predicted), body.task_count
            )
        )
    else:
        predicted = body.predicted_delay_days
        det_summary = body.deterministic_summary or ""

    # Fallback narrative — used when the LLM is off or unreachable.
    headline = _fallback_headline(scenario_type, predicted)
    impact = det_summary or _fallback_simulate_text(
        body.input_delay_days or 0, predicted, pe + timedelta(days=max(0, predicted)), body.task_count
    )

    llm_data = await _llm_json(
        SIMULATE_SYSTEM_PROMPT,
        _build_scenario_user_prompt(body),
    )
    if llm_data:
        h = llm_data.get("headline")
        s = llm_data.get("impact_summary")
        if isinstance(h, str) and h.strip():
            headline = h.strip()[:200]
        if isinstance(s, str) and s.strip():
            impact = s.strip()

    return SimulateOut(
        predicted_delay=predicted,
        impact_summary=impact,
        headline=headline,
        scenario_type=scenario_type,
    )


def _fallback_headline(scenario_type: str, predicted: int) -> str:
    if scenario_type == "UniformSlip":
        return f"Uniform slip → {predicted:+d} day finish"
    if scenario_type == "SingleTaskSlip":
        return f"Single task slip → {predicted:+d} day finish"
    if scenario_type == "AddResource":
        return f"Add resource → {predicted:+d} day finish"
    if scenario_type == "WeatherPause":
        return f"Weather pause → {predicted:+d} day finish"
    if scenario_type == "ScopeReduction":
        return f"Scope reduction → {predicted:+d} day finish"
    return f"Scenario → {predicted:+d} day finish"


# ---------------------------------------------------------------------------
# /auto-suggest — proposes a short list of scenarios worth exploring given
# the current state of a project. The AI service only picks WHICH scenarios to
# try; the .NET side runs them through the deterministic math.
# ---------------------------------------------------------------------------


class AutoSuggestIn(BaseModel):
    project_id: str
    project_name: str
    project_start: str
    project_end: str
    task_count: int = Field(ge=0)
    high_risk_count: int = Field(ge=0)
    medium_risk_count: int = Field(ge=0)
    low_risk_count: int = Field(ge=0)
    avg_progress: int = Field(ge=0, le=100)
    expected_progress: int = Field(ge=0, le=100)
    days_to_finish: int
    tasks: list[dict] = Field(default_factory=list)  # [{id, name, progress}]


class SuggestedScenario(BaseModel):
    scenario_type: str
    label: str
    rationale: str
    config: dict


class AutoSuggestOut(BaseModel):
    suggestions: list[SuggestedScenario]


def _fallback_suggestions(body: AutoSuggestIn) -> list[SuggestedScenario]:
    out: list[SuggestedScenario] = []
    # Always suggest a small uniform slip — the "what if it just slips a week" baseline.
    out.append(SuggestedScenario(
        scenario_type="UniformSlip",
        label="What if every task slips 5 days?",
        rationale="A conservative baseline — small, uniform slippage across trades.",
        config={"InputDelayDays": 5},
    ))
    # Weather pause — common real-world hazard.
    out.append(SuggestedScenario(
        scenario_type="WeatherPause",
        label="What if a 7-day weather pause hits?",
        rationale="Sites with outdoor exposure should size the hit of a bad-weather week.",
        config={"PauseDays": 7},
    ))
    # If we have a laggy project, suggest adding resource.
    if body.expected_progress - body.avg_progress >= 10:
        out.append(SuggestedScenario(
            scenario_type="AddResource",
            label="What if we add 25% crew capacity?",
            rationale=(
                f"Progress is {body.expected_progress - body.avg_progress} pts behind "
                "plan; adding crew tests whether that recovers the slip."
            ),
            config={"CapacityMultiplier": 0.25},
        ))
    # If we have high-risk tasks, suggest slipping the first one as SingleTaskSlip.
    slip_task = next(iter(body.tasks), None)
    if slip_task:
        out.append(SuggestedScenario(
            scenario_type="SingleTaskSlip",
            label=f"What if \"{slip_task.get('name', 'the top task')}\" slips 5 days?",
            rationale="Isolating one task surfaces how critical-path sensitive the plan is.",
            config={"TaskId": slip_task.get("id"), "DelayDays": 5},
        ))
    # If scope is large, suggest scope reduction.
    if body.task_count >= 10:
        out.append(SuggestedScenario(
            scenario_type="ScopeReduction",
            label="What if we drop 2 tasks from scope?",
            rationale="Pressure test the schedule win from light de-scoping.",
            config={"TasksRemoved": 2},
        ))
    return out[:4]


AUTO_SUGGEST_SYSTEM_PROMPT = (
    "You are Simulyn AI, helping a construction project manager pick which "
    "what-if scenarios are worth simulating on their project right now. "
    "Choose scenarios that match the current state of the project (progress gap, "
    "risk levels, days to finish). Never invent project facts."
)


@app.post("/auto-suggest", response_model=AutoSuggestOut)
async def auto_suggest(body: AutoSuggestIn) -> AutoSuggestOut:
    suggestions = _fallback_suggestions(body)

    tasks_brief = ""
    if body.tasks:
        tasks_brief = "\nTop tasks (id, name, progress%):\n" + "\n".join(
            f"  - {t.get('id')}: {t.get('name')} ({t.get('progress', 0)}%)"
            for t in body.tasks[:6]
        )

    user_prompt = (
        f"Project: {body.project_name}\n"
        f"Window: {body.project_start} -> {body.project_end}\n"
        f"Days to finish: {body.days_to_finish}\n"
        f"Tasks: {body.task_count} total "
        f"(High={body.high_risk_count}, Medium={body.medium_risk_count}, Low={body.low_risk_count})\n"
        f"Progress: {body.avg_progress}% vs expected {body.expected_progress}%"
        f"{tasks_brief}\n\n"
        "Suggest 3-4 scenarios the PM should run this week. Respond with JSON:\n"
        '  {"suggestions": [{"scenario_type":..., "label":..., "rationale":..., "config": {...}}]}\n'
        "Allowed scenario_type values: UniformSlip, SingleTaskSlip, AddResource, WeatherPause, ScopeReduction.\n"
        "Config keys per type:\n"
        '  UniformSlip: {"InputDelayDays": int}\n'
        '  SingleTaskSlip: {"TaskId": <task_id from input>, "DelayDays": int}\n'
        '  AddResource: {"CapacityMultiplier": decimal 0.1-1.0}\n'
        '  WeatherPause: {"PauseDays": int}\n'
        '  ScopeReduction: {"TasksRemoved": int}\n'
        "label: short PM-facing question. rationale: one sentence why this matters now."
    )

    llm_data = await _llm_json(AUTO_SUGGEST_SYSTEM_PROMPT, user_prompt)
    if llm_data and isinstance(llm_data.get("suggestions"), list):
        parsed: list[SuggestedScenario] = []
        allowed = {"UniformSlip", "SingleTaskSlip", "AddResource", "WeatherPause", "ScopeReduction"}
        for item in llm_data["suggestions"]:
            if not isinstance(item, dict):
                continue
            st = str(item.get("scenario_type", "")).strip()
            label = str(item.get("label", "")).strip()
            rationale = str(item.get("rationale", "")).strip()
            config = item.get("config")
            if st not in allowed or not label or not isinstance(config, dict):
                continue
            parsed.append(SuggestedScenario(
                scenario_type=st,
                label=label[:140],
                rationale=rationale[:280],
                config=config,
            ))
        if parsed:
            suggestions = parsed[:5]

    return AutoSuggestOut(suggestions=suggestions)


# ---------------------------------------------------------------------------
# /project-brief — one-glance project health narrative
#
# The health score is computed deterministically from the risk mix and the
# progress-vs-window gap so the same project renders the same score every
# time. The LLM only writes the headline, body, and tone tags.
# ---------------------------------------------------------------------------


class ProjectBriefIn(BaseModel):
    project_id: str
    project_name: str
    project_start: str
    project_end: str
    task_count: int = Field(ge=0)
    high_risk_count: int = Field(ge=0)
    medium_risk_count: int = Field(ge=0)
    low_risk_count: int = Field(ge=0)
    unpredicted_count: int = Field(ge=0)
    avg_progress: int = Field(ge=0, le=100)
    expected_progress: int = Field(ge=0, le=100)
    days_to_finish: int  # negative when past the planned end date


class ProjectBriefOut(BaseModel):
    headline: str
    body: str
    health_score: int
    tone_tags: list[str]


def _compute_health_score(body: ProjectBriefIn) -> int:
    """Return a 0-100 health score.

    Three roughly equal signals:
      - Risk mix  (High tasks hurt a lot, Medium a bit, Low not at all)
      - Progress gap (actual vs expected for the time elapsed)
      - Schedule cushion (how close we are to the planned end date)

    Unpredicted tasks get a mild penalty so "no data" doesn't read as "all good".
    """
    total = max(body.task_count, 1)

    high_ratio = body.high_risk_count / total
    med_ratio = body.medium_risk_count / total
    unpred_ratio = body.unpredicted_count / total
    risk_penalty = 100.0 * high_ratio + 40.0 * med_ratio + 15.0 * unpred_ratio
    risk_score = max(0.0, 100.0 - risk_penalty)

    gap = max(0, body.expected_progress - body.avg_progress)
    progress_score = max(0.0, 100.0 - gap * 2.0)

    if body.days_to_finish >= 14:
        cushion_score = 100.0
    elif body.days_to_finish >= 0:
        cushion_score = 60.0 + (body.days_to_finish / 14.0) * 40.0
    else:
        cushion_score = max(0.0, 60.0 + body.days_to_finish * 3.0)

    score = 0.4 * risk_score + 0.4 * progress_score + 0.2 * cushion_score
    return int(round(max(0.0, min(100.0, score))))


def _tone_tags_for(body: ProjectBriefIn, score: int) -> list[str]:
    tags: list[str] = []
    if score >= 80:
        tags.append("On track")
    elif score >= 55:
        tags.append("Watch")
    else:
        tags.append("At risk")

    if body.high_risk_count > 0:
        tags.append(f"{body.high_risk_count} high-risk task" + ("s" if body.high_risk_count != 1 else ""))
    if body.avg_progress + 10 < body.expected_progress:
        tags.append("Behind schedule")
    if body.days_to_finish < 0:
        tags.append("Past planned end")
    elif 0 <= body.days_to_finish <= 7:
        tags.append("Finish week")
    if body.unpredicted_count > 0 and body.unpredicted_count == body.task_count:
        tags.append("No predictions yet")
    return tags[:4]


def _fallback_brief_text(body: ProjectBriefIn, score: int) -> tuple[str, str]:
    if body.task_count == 0:
        return (
            f"{body.project_name}: no tasks yet.",
            "Add tasks or import a schedule to start tracking risk and progress.",
        )
    status = "on track" if score >= 80 else ("needs attention" if score >= 55 else "at risk")
    headline = f"{body.project_name}: {status}"
    parts = [
        f"Average progress {body.avg_progress}% vs expected {body.expected_progress}%.",
    ]
    if body.high_risk_count > 0:
        parts.append(
            f"{body.high_risk_count} task(s) at High risk, {body.medium_risk_count} at Medium."
        )
    if body.days_to_finish >= 0:
        parts.append(f"{body.days_to_finish} day(s) to planned finish.")
    else:
        parts.append(f"{-body.days_to_finish} day(s) past the planned finish.")
    return headline, " ".join(parts)


def _build_project_brief_user_prompt(body: ProjectBriefIn, score: int) -> str:
    return (
        f"Project: {body.project_name}\n"
        f"Window: {body.project_start} -> {body.project_end}\n"
        f"Days until planned finish: {body.days_to_finish}\n"
        f"Tasks: {body.task_count} total "
        f"(High={body.high_risk_count}, Medium={body.medium_risk_count}, "
        f"Low={body.low_risk_count}, Unpredicted={body.unpredicted_count})\n"
        f"Average progress: {body.avg_progress}% (expected {body.expected_progress}% for time elapsed)\n"
        f"Computed health score: {score}/100\n\n"
        "Respond with JSON containing exactly three fields:\n"
        '  "headline":  one short sentence (<= 90 chars), punchy, concrete.\n'
        '               Example: "Interior fitout slipping ~10 days, foundation clean."\n'
        '  "body":      2-3 sentences explaining the current state and the one thing a\n'
        "               busy PM should pay attention to. Use trade language where you can.\n"
        '  "tone_tags": JSON array of 1-3 short labels (<= 20 chars each), e.g.\n'
        '               ["Watch","Behind schedule"].'
    )


@app.post("/project-brief", response_model=ProjectBriefOut)
async def project_brief(body: ProjectBriefIn) -> ProjectBriefOut:
    score = _compute_health_score(body)
    headline, brief_body = _fallback_brief_text(body, score)
    tone_tags = _tone_tags_for(body, score)

    llm_data = await _llm_json(
        PROJECT_BRIEF_SYSTEM_PROMPT,
        _build_project_brief_user_prompt(body, score),
    )
    if llm_data:
        h = llm_data.get("headline")
        b = llm_data.get("body")
        t = llm_data.get("tone_tags")
        if isinstance(h, str) and h.strip():
            headline = h.strip()[:200]
        if isinstance(b, str) and b.strip():
            brief_body = b.strip()[:1800]
        if isinstance(t, list):
            cleaned = [str(x).strip()[:30] for x in t if isinstance(x, (str, int, float)) and str(x).strip()]
            if cleaned:
                tone_tags = cleaned[:4]

    return ProjectBriefOut(
        headline=headline,
        body=brief_body,
        health_score=score,
        tone_tags=tone_tags,
    )


# ---------------------------------------------------------------------------
# /weekly-recap — short dashboard narrative across the whole org
# ---------------------------------------------------------------------------


class WeeklyRecapProject(BaseModel):
    project_id: str
    project_name: str
    high_risk_count: int = Field(ge=0)
    medium_risk_count: int = Field(ge=0)
    low_risk_count: int = Field(ge=0)
    unpredicted_count: int = Field(ge=0)
    task_count: int = Field(ge=0)
    avg_progress: int = Field(ge=0, le=100)
    expected_progress: int = Field(ge=0, le=100)
    days_to_finish: int
    high_risk_delta: int = 0  # change vs 7 days ago (positive = more high-risk now)


class WeeklyRecapIn(BaseModel):
    organization_name: str
    project_count: int = Field(ge=0)
    total_high_risk: int = Field(ge=0)
    total_medium_risk: int = Field(ge=0)
    total_low_risk: int = Field(ge=0)
    total_unpredicted: int = Field(ge=0)
    predictions_this_week: int = Field(ge=0)
    high_risk_delta_week: int = 0  # portfolio-wide change vs 7 days ago
    projects: list[WeeklyRecapProject] = []


class WeeklyRecapOut(BaseModel):
    headline: str
    bullets: list[str]


def _fallback_recap(body: WeeklyRecapIn) -> tuple[str, list[str]]:
    if body.project_count == 0:
        return (
            f"{body.organization_name}: nothing to recap yet.",
            ["Create or import a project to start generating weekly recaps."],
        )
    if body.total_high_risk == 0 and body.total_medium_risk == 0:
        headline = f"{body.project_count} project(s), no open risks."
    else:
        direction = (
            "up" if body.high_risk_delta_week > 0
            else "down" if body.high_risk_delta_week < 0
            else "flat"
        )
        headline = (
            f"{body.total_high_risk} high-risk task(s) across "
            f"{body.project_count} project(s) — {direction} vs last week."
        )
    bullets: list[str] = []
    worst = sorted(body.projects, key=lambda p: -p.high_risk_count)[:3]
    for p in worst:
        if p.high_risk_count == 0:
            continue
        bullets.append(
            f"{p.project_name}: {p.high_risk_count} high-risk, "
            f"{p.avg_progress}% progress vs {p.expected_progress}% expected."
        )
    if not bullets:
        bullets.append(
            f"Portfolio averages look healthy; {body.predictions_this_week} "
            "prediction(s) ran this week."
        )
    return headline, bullets


def _build_weekly_recap_user_prompt(body: WeeklyRecapIn) -> str:
    worst = sorted(
        body.projects,
        key=lambda p: (-p.high_risk_count, -(p.expected_progress - p.avg_progress)),
    )[:5]
    lines = [
        f"Organization: {body.organization_name}",
        f"Projects: {body.project_count}",
        f"Risk totals: High={body.total_high_risk}, "
        f"Medium={body.total_medium_risk}, Low={body.total_low_risk}, "
        f"Unpredicted={body.total_unpredicted}",
        f"High-risk change vs 7 days ago: {body.high_risk_delta_week:+d}",
        f"Predictions run this week: {body.predictions_this_week}",
        "",
        "Top projects to consider (worst first):",
    ]
    if worst:
        for p in worst:
            gap = p.expected_progress - p.avg_progress
            lines.append(
                f"- {p.project_name}: High={p.high_risk_count}, "
                f"Medium={p.medium_risk_count}, progress {p.avg_progress}% "
                f"(expected {p.expected_progress}%, gap {gap:+d}), "
                f"{p.days_to_finish} day(s) to finish, "
                f"high-risk delta {p.high_risk_delta:+d}"
            )
    else:
        lines.append("- (no projects)")
    lines.append("")
    lines.append(
        "Respond with JSON containing exactly two fields:\n"
        '  "headline": one sentence summarising the week (<= 120 chars). No numbers that\n'
        "              are not in the input.\n"
        '  "bullets":  3-5 short bullets (<= 140 chars each) a construction leader would\n'
        "              want to see first. Call out specific projects by name where useful.\n"
        "              Each bullet is plain text, no leading dashes, no markdown."
    )
    return "\n".join(lines)


@app.post("/weekly-recap", response_model=WeeklyRecapOut)
async def weekly_recap(body: WeeklyRecapIn) -> WeeklyRecapOut:
    headline, bullets = _fallback_recap(body)

    llm_data = await _llm_json(
        WEEKLY_RECAP_SYSTEM_PROMPT,
        _build_weekly_recap_user_prompt(body),
    )
    if llm_data:
        h = llm_data.get("headline")
        bs = llm_data.get("bullets")
        if isinstance(h, str) and h.strip():
            headline = h.strip()[:240]
        if isinstance(bs, list):
            cleaned = [str(x).strip().lstrip("-• ").strip()[:200] for x in bs if isinstance(x, (str, int, float)) and str(x).strip()]
            if cleaned:
                bullets = cleaned[:6]

    return WeeklyRecapOut(headline=headline, bullets=bullets)


@app.get("/health")
def health():
    return {
        "status": "ok",
        "version": app.version,
        "llm_provider": PROVIDER,
        "openai_model": OPENAI_MODEL if PROVIDER == "openai" else None,
        "anthropic_model": ANTHROPIC_MODEL if PROVIDER == "anthropic" else None,
        "ollama_model": OLLAMA_MODEL if PROVIDER == "ollama" else None,
        "ollama_chat_model": OLLAMA_CHAT_MODEL if PROVIDER == "ollama" else None,
        "ollama_base_url": OLLAMA_BASE_URL if PROVIDER == "ollama" else None,
    }


# ---------------------------------------------------------------------------
# Chat copilot (/chat-step)
#
# Stateless step in the .NET-orchestrated tool-calling loop. The .NET side
# owns:
#   - executing tools against the org's data (in-process, multi-tenant safe)
#   - looping until the LLM answers (cap at 6 iterations)
#   - persisting nothing server-side (frontend keeps history in localStorage)
#
# This endpoint translates the canonical message + tool format used by the
# .NET API into each provider's native shape (OpenAI / Ollama / Anthropic),
# calls the model, and translates the response back. If no provider is
# configured we return a friendly "off" answer so the UI never blanks.
# ---------------------------------------------------------------------------


class ChatToolDefinition(BaseModel):
    name: str
    description: str
    parameters: dict


class ChatToolCall(BaseModel):
    id: str
    name: str
    arguments: dict


class ChatMessage(BaseModel):
    role: Literal["system", "user", "assistant", "tool"]
    content: Optional[str] = None
    toolCalls: Optional[list[ChatToolCall]] = Field(default=None, alias="toolCalls")
    toolCallId: Optional[str] = Field(default=None, alias="toolCallId")
    name: Optional[str] = None

    model_config = {"populate_by_name": True}


class ChatStepIn(BaseModel):
    messages: list[ChatMessage]
    available_tools: list[ChatToolDefinition] = Field(alias="availableTools")

    model_config = {"populate_by_name": True}


class ChatStepOut(BaseModel):
    type: Literal["tool_call", "answer"]
    tool_calls: Optional[list[ChatToolCall]] = None
    content: Optional[str] = None
    detected_language: Optional[str] = None
    provider: str


def _msgs_to_openai(messages: list[ChatMessage]) -> list[dict]:
    """Translate canonical messages to OpenAI/Ollama chat-completions shape."""
    out: list[dict] = []
    for m in messages:
        if m.role == "assistant" and m.toolCalls:
            out.append({
                "role": "assistant",
                "content": m.content or "",
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.name,
                            "arguments": json.dumps(tc.arguments or {}),
                        },
                    }
                    for tc in m.toolCalls
                ],
            })
        elif m.role == "tool":
            out.append({
                "role": "tool",
                "tool_call_id": m.toolCallId or "",
                "content": m.content or "",
            })
        else:
            out.append({"role": m.role, "content": m.content or ""})
    return out


def _tools_to_openai(tools: list[ChatToolDefinition]) -> list[dict]:
    return [
        {
            "type": "function",
            "function": {
                "name": t.name,
                "description": t.description,
                "parameters": t.parameters,
            },
        }
        for t in tools
    ]


def _msgs_to_anthropic(messages: list[ChatMessage]) -> tuple[Optional[str], list[dict]]:
    """Translate canonical messages to Anthropic shape.

    Returns (system_text, messages). Anthropic takes `system` as its own param
    (not as a message), and tool replies live as `tool_result` content blocks
    inside a `user` message.
    """
    system_parts: list[str] = []
    out: list[dict] = []
    for m in messages:
        if m.role == "system":
            if m.content:
                system_parts.append(m.content)
            continue
        if m.role == "assistant" and m.toolCalls:
            blocks: list[dict] = []
            if m.content:
                blocks.append({"type": "text", "text": m.content})
            for tc in m.toolCalls:
                blocks.append({
                    "type": "tool_use",
                    "id": tc.id,
                    "name": tc.name,
                    "input": tc.arguments or {},
                })
            out.append({"role": "assistant", "content": blocks})
            continue
        if m.role == "tool":
            out.append({
                "role": "user",
                "content": [{
                    "type": "tool_result",
                    "tool_use_id": m.toolCallId or "",
                    "content": m.content or "",
                }],
            })
            continue
        out.append({"role": m.role, "content": m.content or ""})
    system = "\n\n".join(system_parts) if system_parts else None
    return system, out


def _tools_to_anthropic(tools: list[ChatToolDefinition]) -> list[dict]:
    return [
        {
            "name": t.name,
            "description": t.description,
            "input_schema": t.parameters,
        }
        for t in tools
    ]


def _safe_json_loads(raw: Any) -> dict:
    """Tool-call arguments come back as JSON strings from OpenAI; be permissive."""
    if isinstance(raw, dict):
        return raw
    if not raw:
        return {}
    try:
        return json.loads(raw)
    except Exception:
        return {}


_LEAKED_TOOL_CALL_RE = re.compile(
    r'\{\s*"name"\s*:\s*"[a-z_]+"\s*,\s*"(?:parameters|arguments)"\s*:.*?\}',
    re.DOTALL,
)
_THINK_BLOCK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)
_OPEN_THINK_TRUNCATED_RE = re.compile(r"<think>.*", re.DOTALL | re.IGNORECASE)


def _strip_thinking(text: str) -> str:
    """Remove qwen3-style reasoning blocks the user shouldn't see.

    Qwen3 emits `<think>...</think>` reasoning before its visible answer. If the
    model finishes naturally we strip the closed block; if it ran out of tokens
    mid-thought we strip the unterminated tail too so the user doesn't see a
    half-finished reasoning trace.
    """
    cleaned = _THINK_BLOCK_RE.sub("", text or "")
    cleaned = _OPEN_THINK_TRUNCATED_RE.sub("", cleaned)
    return cleaned.strip()


def _scrub_leaked_tool_calls(text: str) -> str:
    """Strip plain-text tool-call JSON that small models sometimes leak.

    e.g. llama3.2:3b will occasionally emit `{"name": "list_projects", "parameters": {}}`
    in its answer text instead of using the structured tool_calls channel. Showing that
    raw protocol text to a user is confusing, so we scrub it before returning.
    """
    cleaned = _LEAKED_TOOL_CALL_RE.sub("", text or "").strip()
    return cleaned


def _is_qwen3(model: str) -> bool:
    return "qwen3" in (model or "").lower()


def _augment_system_for_qwen3(messages: list[dict]) -> list[dict]:
    """Append `/no_think` to qwen3 system prompts to disable thinking-mode.

    Qwen3 has a built-in switch: appending `/no_think` to a user or system
    message tells the model to skip its `<think>...</think>` reasoning block
    and answer directly. Without this on a 4B model + tool-calling, the model
    can spend its entire token budget thinking and produce empty answers.
    See: https://qwenlm.github.io/blog/qwen3/ ("Soft switch").
    """
    augmented: list[dict] = []
    injected = False
    for m in messages:
        if not injected and m.get("role") == "system":
            content = (m.get("content") or "")
            if "/no_think" not in content:
                content = f"{content}\n\n/no_think"
            augmented.append({**m, "content": content})
            injected = True
        else:
            augmented.append(m)
    if not injected:
        augmented.insert(0, {"role": "system", "content": "/no_think"})
    return augmented


async def _chat_openai_compatible(body: ChatStepIn, model: str, base_label: str) -> ChatStepOut:
    """Shared OpenAI / Ollama path — both expose the same chat-completions API."""
    client = _get_openai() if base_label == "openai" else _get_ollama()

    openai_messages = _msgs_to_openai(body.messages)
    if base_label == "ollama" and _is_qwen3(model):
        openai_messages = _augment_system_for_qwen3(openai_messages)

    resp = await client.chat.completions.create(
        model=model,
        max_tokens=CHAT_MAX_TOKENS,
        temperature=0.2,
        messages=openai_messages,
        tools=_tools_to_openai(body.available_tools),
        tool_choice="auto",
    )
    choice = resp.choices[0].message
    finish_reason = getattr(resp.choices[0], "finish_reason", None)

    tool_calls_raw = getattr(choice, "tool_calls", None) or []
    if tool_calls_raw:
        normalized = [
            ChatToolCall(
                id=tc.id,
                name=tc.function.name,
                arguments=_safe_json_loads(tc.function.arguments),
            )
            for tc in tool_calls_raw
        ]
        return ChatStepOut(type="tool_call", tool_calls=normalized, provider=base_label)

    raw = choice.content or ""
    after_think = _strip_thinking(raw)
    cleaned = _scrub_leaked_tool_calls(after_think)

    if not cleaned:
        # Diagnostics: log enough to debug small-model failures without leaking content.
        logger.info(
            "Empty chat reply (provider=%s, model=%s, finish=%s, raw_len=%d, after_think_len=%d)",
            base_label, model, finish_reason, len(raw), len(after_think),
        )
        if finish_reason == "length":
            cleaned = (
                "I needed more room to answer that. Try asking a more specific question — "
                "for example, name a single project or ask for one metric at a time."
            )
        elif raw and not after_think:
            cleaned = (
                "I was thinking that one through but didn't finish in time. "
                "Try rephrasing or breaking the question into smaller parts."
            )
        else:
            cleaned = "I'm here to help with your Simulyn projects. What would you like to know?"

    return ChatStepOut(
        type="answer",
        content=cleaned,
        provider=base_label,
    )


async def _chat_anthropic(body: ChatStepIn) -> ChatStepOut:
    client = _get_anthropic()
    system, msgs = _msgs_to_anthropic(body.messages)
    kwargs: dict = {
        "model": ANTHROPIC_MODEL,
        "max_tokens": CHAT_MAX_TOKENS,
        "temperature": 0.2,
        "messages": msgs,
        "tools": _tools_to_anthropic(body.available_tools),
    }
    if system:
        kwargs["system"] = system
    resp = await client.messages.create(**kwargs)

    text_parts: list[str] = []
    tool_uses: list[ChatToolCall] = []
    for block in resp.content:
        block_type = getattr(block, "type", None)
        if block_type == "text":
            text_parts.append(getattr(block, "text", ""))
        elif block_type == "tool_use":
            tool_uses.append(ChatToolCall(
                id=getattr(block, "id", ""),
                name=getattr(block, "name", ""),
                arguments=getattr(block, "input", {}) or {},
            ))
    if tool_uses:
        return ChatStepOut(type="tool_call", tool_calls=tool_uses, provider="anthropic")
    return ChatStepOut(
        type="answer",
        content="".join(text_parts).strip(),
        provider="anthropic",
    )


@app.post("/chat-step", response_model=ChatStepOut)
async def chat_step(body: ChatStepIn) -> ChatStepOut:
    if PROVIDER == "off":
        return ChatStepOut(
            type="answer",
            content=(
                "AI chat is not configured for this deployment. Ask your admin to set "
                "OPENAI_API_KEY, ANTHROPIC_API_KEY, or LLM_PROVIDER=ollama."
            ),
            provider="off",
        )

    try:
        if PROVIDER == "openai":
            return await _chat_openai_compatible(body, OPENAI_CHAT_MODEL, "openai")
        if PROVIDER == "ollama":
            return await _chat_openai_compatible(body, OLLAMA_CHAT_MODEL, "ollama")
        if PROVIDER == "anthropic":
            return await _chat_anthropic(body)
    except Exception as exc:
        chat_model = (
            OPENAI_CHAT_MODEL if PROVIDER == "openai"
            else OLLAMA_CHAT_MODEL if PROVIDER == "ollama"
            else ANTHROPIC_MODEL if PROVIDER == "anthropic"
            else "-"
        )
        logger.exception(
            "Chat step failed (provider=%s, chat_model=%s); error=%s",
            PROVIDER,
            chat_model,
            exc,
        )
        return ChatStepOut(
            type="answer",
            content=(
                "I hit an error talking to the language model. Try again in a moment, "
                "or ask your admin to check the AI service logs."
            ),
            provider=PROVIDER,
        )

    return ChatStepOut(
        type="answer",
        content="No LLM provider available.",
        provider=PROVIDER,
    )
