namespace Simulyn.Api.Models.Dtos;

public record DashboardSummaryDto(
    int TotalProjects,
    int HighRiskTasks,
    int OpenAlerts,
    int LowRiskTasks = 0,
    int MediumRiskTasks = 0,
    int UnpredictedTasks = 0);

/// <summary>
/// One actionable alert for the dashboard. Split into three fields so the UI
/// can render them independently:
///   - <see cref="TaskName"/> / <see cref="ProjectName"/> provide context,
///   - <see cref="Reason"/> is the AI-generated plain-English risk summary,
///   - <see cref="Recommendation"/> is the mitigation plan (expandable),
///   - <see cref="WhySignal"/> is the deterministic math behind the risk
///     (shown in a "Why?" tooltip so users trust the call).
/// The legacy <see cref="Message"/> field is kept populated for back-compat.
/// </summary>
public record AlertDto(
    string Type,
    string Message,
    Guid? ProjectId,
    Guid? TaskId,
    string RiskLevel,
    DateTime CreatedAt,
    string? TaskName = null,
    string? ProjectName = null,
    string? Reason = null,
    string? Recommendation = null,
    int? DelayDays = null,
    string? WhySignal = null);

/// <summary>
/// One AI-generated insight surfaced to the dashboard. Includes the prediction
/// summary + recommendation plus the project/task context for deep-linking.
/// </summary>
public record InsightDto(
    Guid TaskId,
    string TaskName,
    Guid ProjectId,
    string ProjectName,
    string RiskLevel,
    int DelayDays,
    string? Summary,
    string? Recommendation,
    DateTime CreatedAt);

/// <summary>
/// One day of historical risk counts for the active organization. Used by the
/// dashboard "Risk trend" gradient line chart. Computed on the fly from the
/// existing Predictions table — no separate snapshot table needed.
/// </summary>
/// <param name="Date">ISO date (yyyy-MM-dd) for this snapshot.</param>
/// <param name="HighRiskTasks">Number of tasks whose latest prediction as of end-of-day was High.</param>
/// <param name="MediumRiskTasks">…Medium.</param>
/// <param name="LowRiskTasks">…Low.</param>
public record RiskTrendPointDto(
    string Date,
    int HighRiskTasks,
    int MediumRiskTasks,
    int LowRiskTasks);

/// <summary>
/// Short narrative recap shown at the top of the dashboard. Generated by the
/// AI service, cached in memory per-org for 12 hours; refresh with ?refresh=true.
/// </summary>
public record WeeklyRecapDto(
    string Headline,
    IReadOnlyList<string> Bullets,
    DateTime GeneratedAt,
    bool IsStale);
