namespace Simulyn.Api.Models.Dtos;

/// <summary>
/// Legacy single-scenario run request. Still accepted by POST /api/simulation
/// for back-compat; new callers should use <see cref="RunScenarioRequest"/>.
/// </summary>
public record RunSimulationRequest(Guid ProjectId, int InputDelayDays);

/// <summary>
/// Scenario-aware run request for POST /api/simulation. Supply a
/// <see cref="ScenarioType"/> (one of the five in
/// <c>Simulyn.Api.Models.Scenarios.ScenarioTypes</c>) plus the matching
/// <see cref="Config"/> as a JSON object.
/// <para>Examples:</para>
/// <list type="bullet">
///   <item><c>{ ScenarioType: "UniformSlip", Config: { InputDelayDays: 5 } }</c></item>
///   <item><c>{ ScenarioType: "SingleTaskSlip", Config: { TaskId: "...", DelayDays: 3 } }</c></item>
///   <item><c>{ ScenarioType: "AddResource", Config: { CapacityMultiplier: 0.25 } }</c></item>
///   <item><c>{ ScenarioType: "WeatherPause", Config: { PauseDays: 7 } }</c></item>
///   <item><c>{ ScenarioType: "ScopeReduction", Config: { TasksRemoved: 2 } }</c></item>
/// </list>
/// </summary>
public record RunScenarioRequest(
    Guid ProjectId,
    string ScenarioType,
    System.Text.Json.JsonElement Config);

/// <summary>
/// One scenario result as persisted in the <c>Simulations</c> table. The
/// <see cref="Headline"/> is generated by the LLM (falls back to deterministic
/// text if the AI service is off) and rendered on the scenario card.
/// </summary>
public record SimulationResultDto(
    Guid Id,
    Guid ProjectId,
    int InputDelay,
    int PredictedDelay,
    string? ImpactSummary,
    DateTime CreatedAt,
    string ScenarioType,
    string? Headline = null,
    string? ScenarioConfigJson = null);

/// <summary>
/// Multi-scenario run request used by POST /api/simulation/compare. All
/// scenarios run against the same project, in parallel. The response preserves
/// the request order so the UI can render a stable side-by-side table.
/// </summary>
public record CompareScenariosRequest(
    Guid ProjectId,
    IReadOnlyList<RunScenarioRequest> Scenarios);

public record CompareScenariosResponse(
    Guid ProjectId,
    IReadOnlyList<SimulationResultDto> Results);

public record SuggestedScenarioDto(
    string ScenarioType,
    string Label,
    string Rationale,
    System.Text.Json.JsonElement Config);

public record AutoSuggestScenariosResponse(
    Guid ProjectId,
    IReadOnlyList<SuggestedScenarioDto> Suggestions);
